### ISSUE TITLE
Can you add a AI Community "Themed" Presentation Template for uniformity?

### ISSUE THREAD

**Issue by residentx10** [GlobalAICommunity/Artwork#1]
I'd like to be able to move my decks to a template/layouts with the same format all around. Can you create one for the community:

Look for:

1. Title Layout
2. Title and Section Layout
3. Section Layout

I would like the other layouts but because we're so close to the event I'll just request these three. 
See screenshot attached. 
![AI_Prez_Layout](https://user-images.githubusercontent.com/9274020/70468097-70501580-1a94-11ea-8396-46e0b91c27c8.png)

**Comment by mdragt** [comment]
Hello! You can use the template Alejandro provided: https://github.com/GlobalAICommunity/Artwork/blob/master/Speakers/GlobalAI-Speaker%20template.pptx
